name: Sprig
markdown: redcarpet
pygments: true
navigation:
- text: About
  url: /sprig/about.html
- text: Docs
  url: /sprig/documentation.html
- text: Examples
  url: /sprig/examples.html
- text: Updates
  url: /sprig/updates.html
